global:
  scrape_interval: 5s

scrape_configs:
  - job_name: tfidf
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8000"]

  - job_name: transformer
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8001"]

  - job_name: agent
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:8002"]
